# Generated by Django 2.2 on 2020-08-29 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_at', models.DateTimeField(auto_now_add=True, verbose_name='Время заполнения')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='webapp.Choice', verbose_name='Ответ')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='webapp.Poll', verbose_name='Ответ')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
